### ISSUE TITLE
Assets: Management

### ISSUE THREAD

**Issue by andhartl** [Incubaid/crm#60] opened 2017-09-19 14:17 UTC
Asset Management: 
Integrate Asset management for Hosters Zero-Nodes, Zero-Nodes/Clusters and Operators (100% owned and co-owned)

**Comment by xmonader** [comment] 2017-10-04 11:10
Duplicate of https://github.com/Incubaid/crm/issues/48

**Closed as completed by xmonader** 2017-10-04 11:10 UTC
